version: "3.8"

services:
  flink-jobmanager:
    image: flink:1.17.2-scala_2.12
    container_name: flink-jobmanager
    command: jobmanager
    ports:
      - "${FLINK_JOBMANAGER_PORT:-8081}:8081"
    env_file:
      - ../../config/.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        parallelism.default: 1
      - FLINK_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_1_IP}:9092,${KAFKA_2_IP}:9092,${KAFKA_3_IP}:9092
      - FLINK_CLICKHOUSE_HOST=${CLICKHOUSE_IP}
    networks:
      - flink-network

  flink-taskmanager:
    image: flink:1.17.2-scala_2.12
    container_name: flink-taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
    env_file:
      - ../../config/.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
      - FLINK_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_1_IP}:9092,${KAFKA_2_IP}:9092,${KAFKA_3_IP}:9092
      - FLINK_CLICKHOUSE_HOST=${CLICKHOUSE_IP}
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge
