services:
  flink-jobmanager:
    build: ../../services/flink-job
    image: flink-taxi-job:latest
    container_name: flink-jobmanager
    command: standalone-job --job-classname com.example.TaxiRealtimeJob
    ports:
      - "${FLINK_JOBMANAGER_PORT:-8081}:8081"
    env_file:
      - ../../config/.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        parallelism.default: 1
      - FLINK_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_1_IP}:${KAFKA_1_EXTERNAL_PORT:-9092},${KAFKA_2_IP}:${KAFKA_2_EXTERNAL_PORT:-9094},${KAFKA_3_IP}:${KAFKA_3_EXTERNAL_PORT:-9096}
      - FLINK_CLICKHOUSE_HOST=${CLICKHOUSE_IP}
      - FLINK_CLICKHOUSE_PORT=${CLICKHOUSE_HTTP_PORT:-8123}
      - FLINK_PARALLELISM=1
      - FLINK_TASKMANAGER_SLOTS=2
      - FLINK_WATERMARK_OUT_OF_ORDERNESS_SEC=5
      - FLINK_WINDOW_DEMAND_MINUTES=3
      - FLINK_JDBC_BATCH_SIZE=5000
      - FLINK_JDBC_BATCH_INTERVAL_MS=5000
      - FLINK_KAFKA_TOPIC=taxi-event-data
      - FLINK_KAFKA_GROUP_ID=${FLINK_KAFKA_GROUP_ID:-taxi-realtime-flink}
      - FLINK_ENABLE_CLICKHOUSE_SINK=${FLINK_ENABLE_CLICKHOUSE_SINK:-true}
      - FLINK_CLICKHOUSE_DATABASE=default
      - FLINK_CLICKHOUSE_TABLE=taxi_events
    networks:
      - kafka-network
    restart: unless-stopped

  flink-taskmanager:
    image: flink-taxi-job:latest
    container_name: flink-taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
    env_file:
      - ../../config/.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
      - FLINK_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_1_IP}:${KAFKA_1_EXTERNAL_PORT:-9092},${KAFKA_2_IP}:${KAFKA_2_EXTERNAL_PORT:-9094},${KAFKA_3_IP}:${KAFKA_3_EXTERNAL_PORT:-9096}
      - FLINK_CLICKHOUSE_HOST=${CLICKHOUSE_IP}
      - FLINK_CLICKHOUSE_PORT=${CLICKHOUSE_HTTP_PORT:-8123}
      - FLINK_PARALLELISM=1
      - FLINK_TASKMANAGER_SLOTS=2
      - FLINK_WATERMARK_OUT_OF_ORDERNESS_SEC=5
      - FLINK_WINDOW_DEMAND_MINUTES=3
      - FLINK_JDBC_BATCH_SIZE=5000
      - FLINK_JDBC_BATCH_INTERVAL_MS=5000
      - FLINK_KAFKA_TOPIC=taxi-event-data
      - FLINK_KAFKA_GROUP_ID=${FLINK_KAFKA_GROUP_ID:-taxi-realtime-flink}
      - FLINK_ENABLE_CLICKHOUSE_SINK=${FLINK_ENABLE_CLICKHOUSE_SINK:-true}
      - FLINK_CLICKHOUSE_DATABASE=default
      - FLINK_CLICKHOUSE_TABLE=taxi_events
    networks:
      - kafka-network
    restart: unless-stopped


  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail-flink
    privileged: true
    env_file:
      - ../../config/.env
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    depends_on:
      - flink-jobmanager
    networks:
      - kafka-network
networks:
  kafka-network:
    external: true
    name: kafka-network