services:
  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    env_file:
      - ../../config/.env
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - kafka-network


  promtail:
    image: grafana/promtail:3.3.2
    container_name: promtail-loki
    privileged: true
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
    name: kafka-network

volumes:
  loki-data:
