version: '3.8'

services:
  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - /tmp/loki:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - kafka-network

  promtail:
    image: grafana/promtail:3.3.2
    container_name: promtail
    privileged: true
    ports:
      - "${PROMTAIL_LOKI_PORT:-9084}:9080"
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker:ro
      - ../../services/generator/data:/var/log/generator:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      kafka-network:
        aliases:
          - promtail
          - promtail-loki

networks:
  kafka-network:
    external: true
    name: kafka-network
