# Flink job runtime config (non-network)
parallelism: 1

taskmanager:
  slots: 2

watermark:
  out_of_orderness_sec: 5

window:
  demand_minutes: 3

jdbc:
  batch_size: 5000
  batch_interval_ms: 5000

kafka:
  topic: "taxi-event-data"

clickhouse:
  database: "default"
  table: "taxi_events"
