apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: taxi-pipeline
  labels:
    app: kafka
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kafka
  ports:
    - name: internal
      port: 29092
      targetPort: internal
    - name: controller
      port: 19093
      targetPort: controller
