services:
  nginx-lb:
    image: nginx:alpine
    container_name: ingestor-lb
    env_file:
      - ../../config/.env
    ports:
      - "${NGINX_LB_PORT:-8080}:80"
    volumes:
      - ./templates/nginx.distributed.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    command: sh -c "envsubst '$$INGESTOR_1_IP $$INGESTOR_2_IP $$INGESTOR_3_IP $$INGESTOR_1_PORT $$INGESTOR_2_PORT $$INGESTOR_3_PORT' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - kafka-network
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.2
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://ingestor-lb/nginx_status
    ports:
      - "${NGINX_EXPORTER_PORT:-9113}:9113"
    depends_on:
      - nginx-lb
    networks:
      - kafka-network
    restart: unless-stopped


  promtail:
    image: grafana/promtail:3.3.2
    container_name: promtail-nginx
    privileged: true
    env_file:
      - ../../config/.env
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    depends_on:
      - nginx-lb
      - nginx-exporter
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
    name: kafka-network
