services:
  nginx-lb:
    image: nginx:alpine
    container_name: ingestor-lb
    env_file:
      - ../../config/.env
    ports:
      - "${NGINX_LB_PORT:-8080}:80"
    volumes:
      - ./nginx.single-machine.conf:/etc/nginx/nginx.conf:ro
    networks:
      - kafka-network
    restart: unless-stopped

networks:
  kafka-network:
    external: true
    name: kafka-network
