services:
  nginx-lb:
    image: nginx:alpine
    container_name: ingestor-lb
    env_file:
      - ../../config/.env
    ports:
      - "${NGINX_LB_PORT:-8080}:80"
    volumes:
      - ./nginx.single-machine.conf:/etc/nginx/nginx.conf:ro
    networks:
      - kafka-network
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.2
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://ingestor-lb/nginx_status
    ports:
      - "${NGINX_EXPORTER_PORT:-9113}:9113"
    depends_on:
      - nginx-lb
    networks:
      - kafka-network
    restart: unless-stopped

networks:
  kafka-network:
    external: true
    name: kafka-network
