services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    env_file:
      - ../../config/.env
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus.distributed.yml:/etc/prometheus/prometheus.yml.tmpl:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - prometheus_data:/prometheus
    entrypoint: /entrypoint.sh
    networks:
      - kafka-network

  promtail:
    image: grafana/promtail:3.3.2
    container_name: promtail-prometheus
    privileged: true
    env_file:
      - ../../config/.env
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    depends_on:
      - prometheus
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
    name: kafka-network

volumes:
  prometheus_data:
