services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    env_file:
      - ../../config/.env
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus.distributed.yml:/etc/prometheus/prometheus.yml.tmpl:ro
      - ./rules:/etc/prometheus/rules:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - prometheus_data:/prometheus
    entrypoint: /entrypoint.sh
    depends_on:
      - promtail
    networks:
      - kafka-network

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.7.0
    container_name: kafka-exporter
    env_file:
      - ../../config/.env
    restart: unless-stopped
    command:
      - "--kafka.server=${KAFKA_1_IP}:${KAFKA_1_EXTERNAL_PORT:-9092}"
      - "--kafka.server=${KAFKA_2_IP}:${KAFKA_2_EXTERNAL_PORT:-9094}"
      - "--kafka.server=${KAFKA_3_IP}:${KAFKA_3_EXTERNAL_PORT:-9096}"
    depends_on:
      - promtail
    networks:
      - kafka-network

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: blackbox-exporter
    restart: unless-stopped
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    depends_on:
      - promtail
    networks:
      - kafka-network

  promtail:
    image: grafana/promtail:3.3.2
    container_name: promtail-prometheus
    privileged: true
    env_file:
      - ../../config/.env
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
    name: kafka-network

volumes:
  prometheus_data:
