version: "3.8"

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    env_file:
      - ../../../config/.env
    ports:
      - "${KAFKA_UI_PORT:-8090}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "${KAFKA_1_IP}:${KAFKA_EXTERNAL_PORT:-9092},${KAFKA_2_IP}:${KAFKA_EXTERNAL_PORT:-9092},${KAFKA_3_IP}:${KAFKA_EXTERNAL_PORT:-9092}"
    networks:
      - kafka-network
    restart: unless-stopped

networks:
  kafka-network:
    driver: bridge
    external: true
    name: kafka-network
