include:
  - docker-compose.kafka-1.yml
  - docker-compose.kafka-2.yml
  - docker-compose.kafka-3.yml
  - docker-compose.clickhouse.yml
  - docker-compose.ingestor-1.yml
  - docker-compose.ingestor-2.yml
  - docker-compose.ingestor-3.yml
  - docker-compose.ingestor-nginx.yml
  - docker-compose.flink.yml
  - docker-compose.kafka-ui.yml
