version: '3.8'

services:
  nginx-lb:
    image: nginx:alpine
    container_name: ingestor-lb
    ports:
      - "${NGINX_LB_PORT:-8080}:80"
    volumes:
      - ../../../infra/nginx/nginx.single-machine.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
